### ISSUE TITLE
In iOS keyboard covers the Bottom TextInput, Randomly 

### ISSUE THREAD

**Issue by hanishcodebrew** [FaridSafi/react-native-gifted-chat#1040]
#### Issue Description

Hello Team,

First of all, I would like to thank you for this awesome and useful package. I am using it in one of my project. Sometimes, when I open the keyboard in iOS app, it covers the bottom TextInput. This issue is random. I have checked it on every device.    

#### Steps to Reproduce / Code Snippets

Open the keyboard in iOS app. Try it multiple times. It does not happen every time. 

#### Expected Results

It should not cover the textinput. 

#### Additional Information
It is not iOS device specific. I am attaching the screenshot of the same
![screen shot 2018-12-14 at 11 54 38 am](https://user-images.githubusercontent.com/40761838/49987182-69cdb180-ff98-11e8-82cc-2cb5e744bae4.png)

* Nodejs version: v10.10.0
* React version: 16.5.0
* React Native version: 0.57.0
* react-native-gifted-chat version: ^0.4.3
* Platform(s) (iOS, Android, or both?): iOS

**Comment by msqar** [comment]
Hey, not related to this but im new to this package as well, can you tell me how to modify that whole input text? and adding those actions too? do you have a working example? Also, i noticed it looks weird and i had to add a bottomOffset on Platform.OS 'ios', because on iPhone X + looks quite weird when opening the keyboard.
