### ISSUE TITLE
Upload file

### ISSUE THREAD

**Issue by superandrew** [FaridSafi/react-native-gifted-chat#1250]
#### Issue Description

I would like to be able to upload PDF files in chat.

#### Steps to Reproduce / Code Snippets

I can create an action but the message structure doesn't allow the "file" type.

#### Expected Results

I would like to see a preview of the file, and being able to "open in" with another application, for example a PDF file.

#### Additional Information

* Nodejs version:11
* React version: 16.5
* React Native version: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz
* react-native-gifted-chat version: 0.9.3
* Platform(s) (iOS, Android, or both?):both
* TypeScript version: tslib 1.9.3

**Comment by pzatorski** [comment]
Hey @superandrew I'm actually starting to implementing the same feature in out app. I would suggest to you instead of "sending" the file trough the message send url with uploaded file.

For example:
Create upload function to s3 bucket, then get the url back and send the url via message.

I think this should work. At least this is my plan to build it.

**Comment by jmandivarapu1** [comment]
> Hey @superandrew I'm actually starting to implementing the same feature in out app. I would suggest to you instead of "sending" the file trough the message send url with uploaded file.
> 
> For example:
> Create upload function to s3 bucket, then get the url back and send the url via message.
> 
> I think this should work. At least this is my plan to build it.

Can you share your solution?
