### ISSUE TITLE
How do I create a private chat with gifted chat

### ISSUE THREAD

**Issue by EricChuddy** [FaridSafi/react-native-gifted-chat#1360]
#### Issue Description

[How do I create a private chat? The given tutorial only showed how to create a group chat]

**Comment by BenQoder** [comment]
It is the sam approach... Just with two people

**Comment by EricChuddy** [comment]
Please where do I put the receiver's ID and the sender id

**Comment by zanemiller2018** [comment]
On Fri, Aug 16, 2019, 2:10 PM EricChuddy <notifications@github.com> wrote:

> Issue Description
>
> [How do I create a private chat? The given tutorial only showed how to
> create a group chat]
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/FaridSafi/react-native-gifted-chat/issues/1360?email_source=notifications&email_token=ALVAHSD2MUFONWSNIR2CTMTQE3UPZA5CNFSM4IMLTTX2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HFWQ4QQ>
>

, or mute the thread

**Comment by msqar** [comment]
@EricChuddy I'll help you out because i had the same problem understanding how this works and what's the message structure that gifted-chat handles.

So, first of all, Gifted-Chat is just a UI library, it won't give you any native-socket implementation to send/receive messages from a server, it's just the look&feel.

Now I clarified that, it doesn't matter how many people are in a certain group chat, can be 1-N. So the implementation on frontend would be the same.

The message structure that you would need to build for gifted-chat is the following:

 ```
            _id: 'the created message ID, given by your server message object',
            text: 'the text in the message',
            createdAt: 'date it was created => new Date()',
            sent: 'was sent?',
            received: 'was received?', // i usually use this one as `isRead`
            // user is the person who sent the message. Can be you or any other member within the group
            user: {
                _id: 'the id of the person who sent it',
                name: 'the name of the person who sent it',
                avatar: 'the avatar as absolute path of the one who sent it'
            }
```

What I have is just a chatClient on my app saying:

`this._chatClient.send('chatMessage', messageObject);`

And also of course a listener, meaning, what am i gonna do with that received message.

```
this._chatClient.on('chatMessage', msg => {
     // do whatever with the msg, append it to your messagesList that is feeding the chat.
     What i do here is to execute a 'buildChatMessage' method to create an object that gifted-chat understands. The one I added above.
});
```

And you should be ready to go :)

**Comment by msqar** [comment]
Also, the person who handles your backend server with sockets, needs to create the group chats in the websocket and assign an ID to each of those. So then, it creates a "channel" for 2 people and send the messages back and forth through that groupID and only those 2 people receive those messages.

**Comment by EricChuddy** [comment]
@msqar thanks so much for your reply but I did not understand your explanations and how I am going to integrate your code to my code

**Comment by msqar** [comment]
@EricChuddy i just gave you an example on how i handle the sockets communication with the server. Are you doing the backend ?? how do you handle that? I guess you can also use Firebase. But i can't help you with that. My friend has done the backend and i did the frontend.
On frontend you can use clients such as `socket.io-client` or `chat-client` npms... they both work fine. You can read the documentation on those too if you want to know how they work.
