### ISSUE TITLE
Small jerk in the composer top border and the messages list when composer input changes from filled to unfilled and vice-versa in Android only.

### ISSUE THREAD

**Issue by ajaykumar97** [FaridSafi/react-native-gifted-chat#1564]
#### Issue Description

I am facing a small jerk in the composer top header and the message listing when the Composer Text Input changes from Filled to UnFilled state and vice-versa in Android only. In iOS, everything works fine.

#### Steps to Reproduce / Code Snippets

- Tap on the Composer text input
- Start typing
- When first character is typed into the input and back button is pressed and text input is made empty, small jerk occurs. Whenever the composer size is changes, the jerk occurs.
- However, when I dig deep into the code of the composer and comment the ``onContentSizeChange`` method in the ``Composer.js`` file inside the ``node-modules``, the jerk disappears but the composer height does not changed on hitting Enter or going to new line.
- Code:

```
<GiftedChat
    messages={this.state.messages}
    onSend={messages => this.onSend(messages)}
    user={{
          _id: 1,
     }}
    alwaysShowSend
 />
```

![GiftedChatIssue](https://user-images.githubusercontent.com/38132295/70968750-1f59a600-20c0-11ea-82b2-bd7ae2075025.gif)

#### Expected Results

The composer input should not jerk when composer size changes on Android.

#### Additional Information

* Nodejs version: 10.16.0
* React version: 16.9.0
* React Native version: 0.61.5
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): Android

**Comment by shamilovtim** [comment]
Have you reproduced this on different resolutions, different emulators and on-device? Which emulator are you experiencing this issue on? 

My concern would be that since this only appears in Android it might be related to native code floating point rounding issues.[ I've had those before.](https://github.com/facebook/react-native/issues/27172)

**Comment by shamilovtim** [comment]
@ajaykumar97 Could you post a JSBin or a similar link to your entire component that this is happening in?

**Comment by ajaykumar97** [comment]
@shamilovtim  This is the gist:
(https://gist.github.com/ajaykumar97/cdabbab4a3a38dcf47538f474fc062cf)[https://gist.github.com/ajaykumar97/cdabbab4a3a38dcf47538f474fc062cf]


I am facing this issue on real Android device and in the Android Emulator also.

**Comment by ItachiUchiha91** [comment]
Same problem here on android

**Comment by edoofx** [comment]
im already deleted onContentSizeChange at composer.js , but jerk didnt dissapear

**Comment by shamilovtim** [comment]
I was not able to reproduce this on my Android emulator (Pixel) or on my Android Device (Galaxy J7)

**Comment by edoofx** [comment]
> I was not able to reproduce this on my Android emulator (Pixel) or on my Android Device (Galaxy J7)

emulator or real device , i have same problem .. but comment onContentSizeChange , works well (because i dont using multiline this time, so no problem)

if u want face this problem .. u can try using genymotion device s7

**Comment by ajaykumar97** [comment]
I am still facing this small jerk issue. Please let me know if anyone found the solution for this.

**Comment by LG1710** [comment]
Facing the same problem

**Comment by LG1710** [comment]
Only for multiline TextInput, by default the Composer is multiline and only on Android (?).
In this case, there is small jerk in the Composer top border, this is due to the fact that onContentSizeChange is calling twice and that the event returned (e.nativeEvent) contains a different contentSize.height, 36,9523811340322 when the TextInput is filled and 42,666...
when the TextInput is empty.

So that the test below in GiftedChat.tsx gives priority to the highest value compared to 41.
Math.max(41, Math.min(200,36...)) -> 41
Math.max(41, Math.min(200,42...)) -> 42

```
onInputSizeChanged = (size: { height: number }) => {
    const newComposerHeight = Math.max(
      this.props.minComposerHeight!,
      Math.min(this.props.maxComposerHeight!, size.height),
    )
    const newMessagesContainerHeight = this.getMessagesContainerHeightWithKeyboard(
      newComposerHeight,
    )
    this.setState({
      composerHeight: newComposerHeight,
      messagesContainerHeight: newMessagesContainerHeight,
    })
  }
```

**Comment by MaximAbramchuck** [comment]
Still facing this issue
