### ISSUE TITLE
How to order messages properly? by ID created in DB or by timestamp sent?

### ISSUE THREAD

**Issue by msqar** [FaridSafi/react-native-gifted-chat#1584]
#### Issue Description
The way i'm handling the messaging in my app is by creating a message object, i send it to server, this server creates a unique ID for this message and sends it back through socketIO to my app and that ID which is a simple integer is used by gifted-chat.

So far so good, but the thing is I would like to implement different message statuses, not only isSent or isRead but also, whenever the message is written and send is pressed, it will show the message instantly with a clock like in Whatsapp, meaning, the message will be sent to the server soon. Then when the message is Sent, this message is updated with a gray tick. IsRead would be blue tick.

Now, by doing this, means that I just can't do this with the current behaviour, i need to create certain ID on my "frontend" (the app) so the messages are correctly displayed and ordered by GiftChat.

Is it a proper workaround to use a timestamp (i.e.: 1577839054620) to order all the messages? It would make sense. The "_id" would be that timestamp value, it also since timestamps can only go up due to time, it can be really useful, and super low chances of getting 2 timestamps being the same, unless i'm super unlucky. At least not in the same chat room.

Any ideas? How do you guys order the messages by their IDs?

**Comment by FrenchMajesty** [comment]
In my application I sort messages by the date they are created at, not by the ID because my IDs are manually generated on the frontend whenever a message is written and sent.

My app has similar message behavior to yours in that a message can have multiple states.

-> Message failed to send
-> Message sent
-> Message was seen

Now the problem was that if a message failed, I want to make it known to the user on the frontend so they can press the button to send again. However, how do I determine if a message has been sent or not in the frontend ?
 
Since sockets are somewhat unreliable and don't scale well, I make an HTTP request to my API to check if a particular message exists in the DB. I use the ID to do that here.

So I simply use the timestamp of when the message was created but I do not set the `_id` as the timestamp value. Rather I have function to sort my array of messages by `created_at` date and then feeds that to the `GiftedChat` component.

**Comment by msqar** [comment]
@FrenchMajesty but if you don't set the _id of every message to gifted-chat, how does it know the order? just by createdAt date???

**Comment by FrenchMajesty** [comment]
@msqar Yes an `_id` has to set and it needs to be unique however that doesn't matter in this case.

The chat itself does not do any type of sorting. It simply shows the messages in the order in which it was given. Ig you are using auto increment ID in your database then it will just so happen to be that the messages are in the order of the `id`.

**Comment by msqar** [comment]
@FrenchMajesty Ohh makes sense, yes, what I do now is whenever i receive messages, i iterate through them and I set an ID that is incrementing by 1. But You say it's not necessary :O although, for ordering purposes I prefer doing it like that.. so i load 15 messages, i set the _id from 0-14, then i load 15 more, i set the ID of every message from 0-29, and so on. I update them.

**Comment by davidlruizc** [comment]
@anastely I faced the same issue and after digging into some issues I found a property on `"react-native-gifted-chat": "^0.16.3"` that solved the sort problem `<GiftedChat inverted={false}/>`

**Comment by ceconcarlsen** [comment]
any idea why inverted is `true` by default?
