### ISSUE TITLE
undefined is not an object(evaluating 'ExtraDimensions[dim]')

### ISSUE THREAD

**Issue by shaikhussian** [FaridSafi/react-native-gifted-chat#161]
hai while using  using this module in android i am getting an error like this in simulator
![screen shot 2016-07-19 at 11 33 42 am](https://cloud.githubusercontent.com/assets/11956308/16940262/387d2d28-4da6-11e6-9543-6cf04440c71f.png)

Please give me suggestions that how to resolve it

**Comment by shaikhussian** [comment]
please respond

**Comment by ggsrivas** [comment]
I faced the same problem. Reason for this issue was,
https://github.com/FaridSafi/react-native-gifted-messenger/blob/master/GiftedMessengerExample/GiftedMessengerContainer.js#L22

Quick workaround which I used was commenting that line and adding below line instead,
var STATUS_BAR_HEIGHT = 30; //ExtraDimensions.get('STATUS_BAR_HEIGHT');

This will load the app but you still need to figure out exact height of status bar.

**Comment by Tamal** [comment]
You have to install this 2 packages and configure android project. Please follow docs. Don't hardcode states bar height.

```
var GiftedMessenger = require('react-native-gifted-messenger');
var Communications = require('react-native-communications');
```
