### ISSUE TITLE
Seed chat history?

### ISSUE THREAD

**Issue by tabrza** [FaridSafi/react-native-gifted-chat#1749]
Is there a way to Seed/save/rehydrate/keep/preserve the chat history from local storage or a cookie or something?

I'm thinking of a use case where the user is browsing from page to page and the chat history has to be preserved across page reloads so the user isn't presented with a clear chat every time.

I am looking to use this with Amazon Lex in react

**Comment by mkhoussid** [comment]
If you're using Redux, you can try [redux-persist](https://www.npmjs.com/package/redux-persist).

If you're using Expo, an alternative is to use their [SecureStore API](https://docs.expo.io/versions/latest/sdk/securestore/), or directly work with the [iOS keychain](https://developer.apple.com/documentation/security/keychain_services) or [Android SharedPreferences](https://developer.android.com/training/data-storage/shared-preferences).

**Comment by tabrza** [comment]
What about using this in a react project?

**Comment by mkhoussid** [comment]
For Reactjs, `window.localStorage` is analogous to SecureStore.

Or you can also use redux-persist.

**Comment by tabrza** [comment]
thanks!

**Comment by Hirbod** [comment]
SecureStore is limited in size. Use AsyncStorage instead

```import { AsyncStorage } from "react-native";```

**Comment by mkhoussid** [comment]
True, but it's worth noting that `AsyncStorage` doesn't encrypt the data.

If you're reluctant to use Expo's `SecureStore` because of the data size limit, you can look into [`expo-unlimited-secure-store`](https://www.npmjs.com/package/@neverdull-agency/expo-unlimited-secure-store), which _also_ plays equally as nicely with `redux-persist` as with Expo's OOTB `SecureStore`.

**Comment by Hirbod** [comment]
True!
