### ISSUE TITLE
Chat messages flickering when UI updates

### ISSUE THREAD

**Issue by mkhoussid** [FaridSafi/react-native-gifted-chat#1781]
#### Issue Description

When a user receives a message with an image in it, I update the UI with the message bubble, and in the bubble the user sees a spinner, while the image is being downloaded. Once the local URI is available, I re-update the UI and set that message's image property to that local URI.

The problem here is that once I update the image property, all of the chat messages flicker (re-render).

Does anyone know how I can get around this? I want just that one message to rerender, not the whole component.

#### Steps to Reproduce / Code Snippets

1. User receives a new message object with an S3 image URI over a socket connection.
2. The message is rendered in the UI with a spinner as a placeholder, while the image is being downloaded.
3. Once a local URI is available, it is set as the value to the object message `image` property.

#### Expected Results

I'd expect the whole GiftedChat component to not re-render, but the UI, instead, flickers/rerenders.

#### Additional Information

* Nodejs version: v13.13.0
* React version: v16.9.0
* React Native version: Expo SDK 37
* react-native-gifted-chat version: v0.13.0
* Platform(s) (iOS, Android, or both?): iOS and Android

**Comment by amirduran** [comment]
I have exactly the same scenario as you but only last image message is rerendered because URL changed all other messages are not flickering.

In my case as soon as user adds image, the local URI is used to display it in chat and I send this image to S3. When I get the S3 url back, i send it to the app and update local URI of that specific image with new S3 URL. What happens here iS that message is 1 second white and the is displayed fine but for now I can live with that.
