### ISSUE TITLE
How to change sent, received, seen status when send a message?

### ISSUE THREAD

**Issue by arunkmoury** [FaridSafi/react-native-gifted-chat#1802]
#### Issue Description

When the user sends a message to another person he can include the **sent, received, seen** properties in the current message object but he can update each of them. Like once user press send sent all will be false. Then once the message added to the firebase then sent should be true, once another user receives this message received should be true, and once other users see this message ie message loaded on the visible screen seen status should change. **I am unable to get at which event we should change these properties & how?**

```
<GiftedChat
                    messages={this.state.messages}
                    onSend={messages => this.onSend(messages)}
                    user={{_id: this.state.user.id}}
                    messagesContainerStyle={{backgroundColor: '#fff'}}
                    renderMessage={this._renderMessage}
                    renderMessageText={this._renderMessageText}
                    renderAvatar={this._renderAvatar}
                    renderTime={()=>null}
                    renderDay={()=>null}
                    showUserAvatar={true}
                    showAvatarForEveryMessage={false}
                    renderBubble={this.renderBubble}
                    placeholder='Enter message'
                    renderInputToolbar={this._renderInputToolbar} 
                    textInputStyle={styles.textInputStyle}
                    renderActions={this._renderAction}
                    // minInputToolbarHeight={44}
                    alwaysShowSend={true}
                    renderSend={this._renderSend}
  />

```

#### Additional Information

* React version:16.11.0
* React Native version: 0.62.2
* react-native-gifted-chat version: 0.16.1
* Platform(s) (iOS, Android, or both?): Android (ios not tested)

**Comment by novlihalsi** [comment]
i have same problem, are you have solved the problem?

**Comment by RupamShaw** [comment]
need to update  message with 
```
newMessage = {
          _id: chat.id,
          text: chat.chatMessage,
          createdAt: chatCreatedTime,
          user: {
            _id: userId,
            name: displayName,
            avatar: userAvatar,
          },
          sent: true,
          received: JSON.parse(`${chat.isRead}`),
        }
```

**Comment by danielmejiadev** [comment]
Please check the update on docs, we already add theses properties into the message object
export interface IMessage {
  _id: string | number
  text: string
  createdAt: Date | number
  user: User
  image?: string
  video?: string
  audio?: string
  system?: boolean
  sent?: boolean
  received?: boolean
  pending?: boolean
  quickReplies?: QuickReplies
}

So you can have listeners in order to change the values for each different state.

For example

`
import React, { useState, useCallback, useEffect } from 'react'
import { GiftedChat } from 'react-native-gifted-chat'

export function Example() {
  const [messages, setMessages] = useState([]);

  useEffect(() => {
      firebase.addListener('onMessageSent', (messageId) => {
         updateMyMessage(messageId, { sent: true })
      })

   firebase.addListener('onMessageReceived', (messageId) => {
         updateMyMessage(messageId, { received: true })
      })
  }, [])
  const updateMyMessage = (messageId, newValues) => {
    // Here your implementation to update the state messages.
 }

  const onSend = useCallback((messages = []) => {
   const [messageToSend] = messages;
   messageToSend.pending = true;
    setMessages(previousMessages => GiftedChat.append(previousMessages, messages))
  }, [])

  return (
    <GiftedChat
      messages={messages}
      onSend={messages => onSend(messages)}
      user={{
        _id: 1,
      }}
    />
  )
}
`

**Comment by eminx** [comment]
How do we know when the other user we have sent message to have read the message? Some sort of sensor?
In other words, I'm looking for something like: https://github.com/joshwnj/react-visibility-sensor

Any suggestions for react-native?
@danielmejiadev @arunkmoury @RupamShaw

**Comment by ankit-ashutec** [comment]
> How do we know when the other user we have sent message to have read the message? Some sort of sensor? In other words, I'm looking for something like: https://github.com/joshwnj/react-visibility-sensor
> 
> Any suggestions for react-native? @danielmejiadev @arunkmoury @RupamShaw
@eminx Any suggestions on this ?
