### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by gminator** [FaridSafi/react-native-gifted-chat#1909]
Is there a way to get local notifications to the phone when new messages are received?

**Comment by leelandclay** [comment]
If you're talking about Phone notifications, not from a chat app. That has to go through Apple or Google. The quick story is that you would set up a trigger that will send the notification to Apple/Google and then they will send it down to the phone.

The long story is this (free typing this...hopefully I won't forget a step):
1. Setup Google Messaging/Apple APN connections through your Play/App Store account
2. Modify your app code to register with the services when they are installed (will ask for permission)
3. When user approves, you get a token...store that in your database
4. Modify your app code to receive the notifications from Google/Apple
5. Setup a trigger so that when a new message is received, you query the database to get the receiver's token and use it with the notification data you want sent to call into the Apple/Google server.

There's a lot of other little things that you can do like deep linking to make it so that when the app is opened from a notification that it goes to the proper chat and such. All of the steps here depend on how you wrote your app (native/framework/etc). If you just do a search for "Send phone notification with Swift" (or whatever language/framework you're using) it will show a more concise walk through of how to get it done.
