### ISSUE TITLE
renderAvatar function not executed when author's image is null

### ISSUE THREAD

**Issue by amirduran** [FaridSafi/react-native-gifted-chat#1939]
#### Issue Description

`renderAvatar` function is available for developers to override default functionality. This function is handy if we want to render our own user image with additional functionalities. Sometimes, message author doesn't have an avatar image where I want to display author initials. The problem is that the function `renderAvatar` is not even being called when message author doesn't have an avatar (avatar is `null`) which is the reason part of the code that should render user initials is never being executed and author's image is never being rendered. 

#### Steps to Reproduce / Code Snippets

Just set message author avatar to null and then override `renderAvatar ` and you will see that this function is never being executed.

#### Expected Results

Expected result is that overriden `renderAvatar` function is called no matter whether avatar of the message author is `null `or not.

#### Additional Information

* Nodejs version: v14.4.0
* React version: 16.11
* React Native version: 0.62.2
* react-native-gifted-chat version:0.16.3
* Platform(s) (iOS, Android, or both?): Both
* TypeScript version: 3.9.5

**Comment by MattAgn** [comment]
I think the advantage of the current implementation is that anyone using a custom renderAvatar does not have to check if the user truly has an avatar since it's already checked by the library. 
But I agree with you that it would be useful to have that possibility. Maybe through a more global render method that would accept avatar being null? Or change the existing method, but then that would compel the library users to changer their renderAvatar method to check for null/undefined... 
Either way I would be glad to help implement the chosen solution if there is any :)

**Comment by diivyu** [comment]
I am also facing the same issue. Do we have any solution for this ?

**Comment by ctl-minh** [comment]
Just a workaround. You can set the avatar prop to `undefined`, instead of `null`, then `renderAvatar` will be called.
