### ISSUE TITLE
Question - Can I use this lib to hook up to my own chat service?

### ISSUE THREAD

**Issue by ajp8164** [FaridSafi/react-native-gifted-chat#2001]
I would like to use this lib as the front end for Freshchat. Can I wire up the Freshchat API (own expense) to this library or is it backed completely by another service (Stream Chat)?

It looks like messages and onSend props do most of the work. Request messages from service (Freshchat) and render gift chat with (marshaled) messages.

When the user taps send just call my onSend handler to send to my service (Freshchat).

Is this essentially it? Seems simple enough..

**Comment by shamilovtim** [comment]
Lots of people use this library in production for homemade chat solutions. Wiring up the business logic is 100% up to you and hence this is really a question for yourself rather than the maintainers. This library does not request messages from a chat service or do anything like that. It gives you visual components so long as you provide data of a shape that conforms to this library and then pass it statefully. The docs are very clear on this and so make a proof of concept and see where you land

**Comment by taatiq882** [comment]
Hi, did you find a sol for connecting fresh chat with Gift chat UI ?
