### ISSUE TITLE
onPress prop not working for Android

### ISSUE THREAD

**Issue by jamesdmurphy51** [FaridSafi/react-native-gifted-chat#2008]
#### Issue Description

onPress prop not working for Android.  Press a message bubble and attached function does not run.

#### Steps to Reproduce / Code Snippets

```
            <GiftedChat
              messages={this.formatMessagesFromRedux()}
              onSend={messages => this.onSend(messages)}
              onLongPress={(context, message) =>
                this.onLongPressMsg(context, message)
              }
              onPress={(context, message) => {
                Alert.alert('Bubble pressed');
              }}
              user={{name: this.props.myNameText, _id: this.props.myUserId}}
              renderBubble={this.renderBubble}
              showUserAvatar={true}
              renderAvatar={props => {
                const avatarProps = props.currentMessage;
                if (avatarProps.user.avatar) {
                  return (
                    <Avatar
                      rounded
                      source={{uri: avatarProps.user.avatar}}
                      size="large"
                    />
                  );
                }
                return null;
              }}
            />
```

#### Expected Results

Alert is triggered

#### Additional Information

* Nodejs version: 10.16
* React version: 16.13.1
* React Native version: 0.63.3
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): Android (havent checked ios)
* TypeScript version: n/a

**Comment by yalisun** [comment]
I think that is because react-native-gifted-chat 0.16.3 doesn't support onPress.

**Comment by jamesdmurphy51** [comment]
?? but isnt 0.16.3 the latest version ??

**Comment by matfin** [comment]
Exact same problem I am having. Here is some sample code to demonstrate what is going on:

```
<Bubble
  {...props}
  usernameStyle={{ color: colors.messageBackground }}
  textStyle={{ left: styles.bubbleText, right: styles.bubbleText }}
  wrapperStyle={{
    left: styles.leftBubbleWrapper,
    right: styles.rightBubbleWrapper,
  }}          
  renderTime={() => null}
  renderMessageText={() => null}
           
  renderCustomView={(): JSX.Element => (
    <TouchableOpacity onPress={(): void => console.log('Press!!')}>
      <View style={{ width: 100, height: 100 }}>
        <Text>Some sample text</Text>
      </View>
    </TouchableOpacity>
  )}
/>
```

Any idea what's going on. The documentation is not too extensive about providing a clue for what could be going on.

**Comment by matfin** [comment]
So, upon further investigation to this, I have found the issue.

If you look inside the file `react-native-gifted-chat/lib/Bubble.js` in the source code - focusing on lines 275 to 287.

Because the call to render the bubble content sits inside `<TouchableWithoutFeedback />`, it seems to prevent `<TouchableOpacity onPress={(): void => doSomething()} />` from working.

When I commented this out, `<TouchableOpacity />` was working as it should in Android again.

**Comment by matfin** [comment]
I have a fix for this.

If you have something like what I have below, then it will work

The modification adds: `touchableProps={{ disabled: true }}` which will disable the `<TouchableWithoutFeedback>...</TouchableWithoutFeedback>` and so your nested `<TouchableOpacity>` will work. Hope this helps!

```
<Bubble
  {...props}
  usernameStyle={{ color: colors.messageBackground }}
  textStyle={{ left: styles.bubbleText, right: styles.bubbleText }}
  wrapperStyle={{
    left: styles.leftBubbleWrapper,
    right: styles.rightBubbleWrapper,
  }}          
  renderTime={() => null}
  renderMessageText={() => null}
  touchableProps={{ disabled: true }} // <= put this in to fix!
  renderCustomView={(): JSX.Element => (
    <TouchableOpacity onPress={(): void => console.log('Press!!')}>
      <View style={{ width: 100, height: 100 }}>
        <Text>Some sample text</Text>
      </View>
    </TouchableOpacity>
  )}
/>
```

**Comment by jamesdmurphy51** [comment]
Unfortunately this didnt work for me.  Adding `touchableProps={{ disabled: true }}` actually made it worse as onLongPress doesnt work either

**Comment by nerdaliciousCH** [comment]
Could it be that the touchable area is not filling out the whole bubble, because that is an issue I am facing. For Android the touchable area wraps the content, i.e. for short text the touchable are is miniscule compared to the surrounding bubble.

**Comment by jamesdmurphy51** [comment]
No its not that either.
Wish the authour would fix this......guess hes given up supporting the library.
Does anyone know another similar library thats still being supported?

**Comment by Yogesh-Dubey-0804** [comment]
Well i have checked out the whole code nowhere onPress is mentioned wtf ?

**Comment by Yogesh-Dubey-0804** [comment]
Well i have solved this issue it took me almost an hour guys but we did it '
so the solution is quite simple 

1.  go to GiftedChat.d.ts at   ''node_modules\react-native-gifted-chat\lib\GiftedChat.d.ts''  ###  **add onPress event**
   
<img width="736" alt="image" src="https://user-images.githubusercontent.com/88256165/147516287-7078e79b-7ffe-46b7-b79b-d9a553ef43ea.png">

2.  Now at the same file under declaration of giftedChat at line no. 114 under static default props add the onPress event
<img width="965" alt="image" src="https://user-images.githubusercontent.com/88256165/147516523-d547936a-683c-4c13-9de0-14ad7404e398.png">

3. Now under static prop types  below add the onPress EVENT 
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/88256165/147516645-c9e923e8-f674-4c5f-a109-e3a87211512e.png">
 
**_Now we are ended with this file now open the bubble.js file at "node_modules\react-native-gifted-chat\lib\Bubble.js"_**

1.         this.onPress = () => {
            const { currentMessage } = this.props;
            if (this.props.onPress) {
                this.props.onPress(this.context, this.props.currentMessage);
            }
            else if (currentMessage && currentMessage.text) {
                const { optionTitles } = this.props;
                const options = optionTitles && optionTitles.length > 0
                    ? optionTitles.slice(0, 2)
                    : DEFAULT_OPTION_TITLES;
                const cancelButtonIndex = options.length - 1;
                this.context.actionSheet().showActionSheetWithOptions({
                    options,
                    cancelButtonIndex,
                }, (buttonIndex) => {
                    switch (buttonIndex) {
                        case 0:
                            Clipboard.setString(currentMessage.text);
                            break;
                        default:
                            break;
                    }
                });
            }
            
        };

2. Add the above code in the constructor at bubble.js below this.onLongPre.. like this way 
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/88256165/147517225-afbfc472-78b1-4684-ae4f-8c5079edc72e.png">


3.  then add in touchable without feedback like this way 
4.  onPress= {this.onPress}
<img width="932" alt="image" src="https://user-images.githubusercontent.com/88256165/147517375-91ea003c-ea4e-4100-8291-9fbce81671c7.png">

5. Then under Bubble.defuault Props  add 
6.       onPress: null,
7.   this way
<img width="892" alt="image" src="https://user-images.githubusercontent.com/88256165/147517502-fe06008e-74fa-4f0e-8674-41f29be3673a.png">

8.  Then under Bubble.PropTypes add onPress  
9.        onPress: PropTypes.func,
10. this way 
<img width="788" alt="image" src="https://user-images.githubusercontent.com/88256165/147517589-7727cb18-cbda-4189-9adb-4de4f3128b22.png">


**Now guys lets move to another file  Bubble.d.ts at ''node_modules\react-native-gifted-chat\lib\Bubble.d.ts''**
1. Add onPress underStatic defualt props
2.          onPress: null;
3. this way 
<img width="579" alt="image" src="https://user-images.githubusercontent.com/88256165/147517686-40d5c8c7-bbad-4e61-84e7-aadf75099d65.png">

4. now under static PropTypes add 
5.         onPress: PropTypes.Requireable<(...args: any[]) => any>;
6. this way 
<img width="890" alt="image" src="https://user-images.githubusercontent.com/88256165/147517753-b6ced25d-572f-4763-a41b-4c5f25a2fbba.png">

7. Now add 
8.       onPress: () => void

8.  this way 
<img width="917" alt="image" src="https://user-images.githubusercontent.com/88256165/147517892-33278b20-30e2-477f-995b-990e3dbe31e8.png">

9.  Also not forget to add  onPress under exporting interface 
10.     onPress?(context?: any, message?: any): void;

10.  this way 
<img width="890" alt="image" src="https://user-images.githubusercontent.com/88256165/147517989-164e2c23-dadf-42ea-8d2e-0a2d08b91138.png">

**_Now lets move to another file Bubble.js.flow this is the last file in which we have to list a change in order to fix this issue_** 

1. add the
2.        onPress?: (context?: any, message?: any) => void,

2. this way 
3. 
<img width="883" alt="image" src="https://user-images.githubusercontent.com/88256165/147518055-8b59adf8-ffd2-44ec-80bb-ae5c306a09e3.png">

**Comment by jamesdmurphy51** [comment]
Genius - that worked

**Comment by 2byrds** [comment]
@Johan-dutoit would you consider merging a pull request with this fix?

**Comment by Johan-dutoit** [comment]
![Screenshot 2022-04-29 at 14 49 52](https://user-images.githubusercontent.com/1611055/165957722-80707bed-f119-4880-8150-15d008873cbf.png)

**Comment by 2byrds** [comment]
thank you for the post.  i'll dig deeper into my setup.

**Comment by Johan-dutoit** [comment]
It might be an issue with 16.3, try install the latest beta.
