### ISSUE TITLE
How to change the date of messages to the text "today"?

### ISSUE THREAD

**Issue by MbIWaTUK** [FaridSafi/react-native-gifted-chat#2029]
![today](https://user-images.githubusercontent.com/53084176/113697645-88659280-96e4-11eb-8f83-3159e954638d.png)

**Comment by MbIWaTUK** [comment]
guys?

**Comment by apappas1129** [comment]
I haven't tried using the `dateFormat` prop of [`GiftedChat`](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/GiftedChat.tsx) component. Try to use that one. But the problem is - when you inspect the source code of the [`Day`](https://github.com/FaridSafi/react-native-gifted-chat/blob/5ba0c245d1a0e647c44a5c00d28a0497faadf6c0/src/Day.tsx) component, you'll see it is using DayJS. And as far as I can tell, it does not have available formatting to display relative time/date like "today", "_n_ days ago", etc... (See [DayJS Format](https://day.js.org/docs/en/display/format))

So maybe you will end up using the `renderMessage` prop to create your own custom [`Message`](https://github.com/FaridSafi/react-native-gifted-chat/blob/5ba0c245d1a0e647c44a5c00d28a0497faadf6c0/src/Message.tsx) with your custom `renderDay` prop, returning you own completely custom component that will replace the [`Day`](https://github.com/FaridSafi/react-native-gifted-chat/blob/5ba0c245d1a0e647c44a5c00d28a0497faadf6c0/src/Day.tsx) component. Just copy the whole component and make it your own by just replacing the dayjs part with your own formatting or maybe with another library like [javascript-time-ago](https://www.npmjs.com/package/javascript-time-ago), [timeago.js](https://www.npmjs.com/package/timeago.js), or even with [react-timeago](https://www.npmjs.com/package/react-timeago).

Then you'll have something like:

```jsx
export const renderMessage = (props) => (
  <Message
    {...props}
    renderDay={(props) => <MyDay {...props} />}
  />
);
```

or something....

**Comment by MbIWaTUK** [comment]
@apappas1129  thank you very much

**Comment by melyux** [comment]
This should be part of the library as it's table stakes for chats these days. @MbIWaTUK mind reopening it?
