### ISSUE TITLE
TextInput not auto height of multi lines (more than five lines)

### ISSUE THREAD

**Issue by charlesluo2014** [FaridSafi/react-native-gifted-chat#235]

**Comment by jeaye** [comment]
This ticket isn't very descriptive, but I think it's addressing the same problem I'm having. Yes, I can type multiple lines, but the text input doesn't change its height as I do. As such, I can only ever see the top line and any additional lines I type are under the keyboard. I haven't seen any docs for handling this case. Can you provide any info?

**Comment by amitava82** [comment]
Still nothing on this?

**Comment by xcarpentier** [comment]
@jeaye Can you provide a screenshot please?

**Comment by jeaye** [comment]
@xcarpentier I don't think I have this issue anymore; I believe my fix was to upgrade RN (I was likely on 0.44.x when this showed up, and I think it was gone by 0.47.x -- now on 0.50.4 and it's not there).

The issue I do have is with the text input not growing more than five lines, as shown here:
![screen](https://user-images.githubusercontent.com/1057635/34274979-14670a3c-e650-11e7-9bc4-fcff5a177550.png)


The only style I have is:
```js
{style: {flex: 1}, contentContainerStyle: {flexGrow: 1, justifyContent: "flex-end"}}
```

**Comment by xcarpentier** [comment]
@jeaye can you open an other issue with 5 lines limit?

**Comment by jeaye** [comment]
On second look, the title of this ticket isn't very clear English, but I think this does seem to be the same problem I'm having now. To break things down:

*TextInput not auto height of multi lines* => There's an issue where the text input's height doesn't automatically update to fit multiple lines

*(more than five lines)* => It happens specifically when there are more than five lines

As shown in my screenshot, that's exactly the problem I have. My reporting that this problem was fixed for me, at this point, seems erroneous and I apologize for the confusion. Rather than open another ticket, we could likely keep this. Let me know how you'd like to handle it, @xcarpentier.
