### ISSUE TITLE
Style variable name conflicting in Send and MessageText

### ISSUE THREAD

**Issue by jeromegrosse** [FaridSafi/react-native-gifted-chat#256]
#### Issue Description

Conflict over the property: `TextStyle` as it modify both the text within the Bubble and the Text within the Send button.
#### Steps to Reproduce / Code Snippets

Pass the property `TextStyle` to GiftedChat. If it is passed so as to validate the properties of `MessageText` (i.e.: With a `left` and `right`), the Send button won't be correctly displayed. On the other case, `TextStyle` is passed so as to modify the style of the Send button, it won't validate and `MessageText` and ReactNative will throw an error.
#### Expected Results

Have two different style name for MessageText and Send so as to not have a conflict and be able to modify them independently.
#### Additional Information
- React Native version: 0.34.1
- react-native-gifted-chat version: 0.0.10
- Platform(s) (iOS, Android, or both?): both

**Comment by kfiroo** [comment]
@jeromegrosse I would suggest you pass `renderSend` and render the `Send` component with the props you need.

**Comment by jpamarohorta** [comment]
A similar problem affects `containerStyle` from Send and  `containerStyle` from InputToolbar. 

Maybe we could create a naming rule for style props like <ComponentNameStyleName>. For this example the props would change to `sendContainerStyle` and `inputToolbarContainerStyle`.

Any issues with this change?

**Comment by lukasbalaz** [comment]
@kfiroo do you mean that I should first pass `containerStyle` prop to `InputToolbar` and then override `renderSend` function just to get rid of it ? Doesn't look very clean to me, I think it would be better not to pass custom style props to `render{Component}` methods at all because:
1. It is not clear that this is how it works. I just spent an hour debugging why is the the Send button styled weirdly when I change the InputToolbar style.
2. You almost never want to pass the same `containerStyle` prop to both parent and child, and if you really do, then you can override the `render` method and not the other way around

What do you think ?

**Comment by Nabellaleen** [comment]
The bug is still there, this issue should not be closed.

Many components are receiving "containerStyle" prop, but with various typing (PropTypes.shape left/right in Avatar or Message, ViewPropStyle in InputToolbar or Day, for examples)

This should be fixed :)
