### ISSUE TITLE
Changing avatar color

### ISSUE THREAD

**Issue by JenilynnB** [FaridSafi/react-native-gifted-chat#266]
I'm trying to change the background color of the avatar when there is no image present. I followed the same pattern as the renderBubble method in the example to create a renderAvater method. Here's how I've implemented it:

```
  renderAvatar(props){
    return (
      <Avatar
        {...props}
        imageStyle={{
          left: {
            backgroundColor: '#355376',
          },
        }}
      />
    );
  }
```

This works to change the background color, but I'm getting a warning that says "Warning: Failed prop type: Invalid prop 'left' of type 'object' supplied to 'Avatar', expected 'number'". I'm guessing that I'm implementing this incorrectly, but the problem is that it works, just gives a warning.

What's the right way to go about this?

**Comment by dgdavid** [comment]
@JenilynnB I think this is happening because the `imageStyle` prop validation.

As you can see in [`Avatar.js` file, line 84](https://github.com/FaridSafi/react-native-gifted-chat/blob/91312c16f041bd78c61d98d0cbdf3f539a7f0f24/src/Avatar.js#L84), this prop must be one of `View.propTypes.style` or `Image.propTypes.style`. Then, if you go to [react-native ViewStylePropTypes](https://github.com/facebook/react-native/blob/43d79da5ba62d655b8c507764138ee31cfa21456/Libraries/Components/View/ViewStylePropTypes.js#L24) you can notice that it relies in `LayoutPropTypes` and, finally, there is, [in line 66](https://github.com/facebook/react-native/blob/43d79da5ba62d655b8c507764138ee31cfa21456/Libraries/StyleSheet/LayoutPropTypes.js#L66) the `left` property validation (`ReactPropTypes.number`).

If the validation is replaced to, for example, `React.PropTypes.object`, the warning dissapears.

Probably, @FaridSafi, @kfiroo or someone else could fix this in the better way possible.
