### ISSUE TITLE
How to create own Message Bubble

### ISSUE THREAD

**Issue by theobouwman** [FaridSafi/react-native-gifted-chat#316]
How can I create my own bubble.
I know there are props like `renderBubble`, `renderMessage` and `renderMessageText` but which parameters do they get?
I can't find a good and rich documentation on this.

**Comment by dgdavid** [comment]
Yes, the documentation needs to be improved. 

If you take a look across commits, issues and PR, you could check that project was in standby a few months. Probably, @FaridSafi has been too busy, since it seems that he is preparing a React Native full-day workshop apart of working in other projects, I suppose. In fact, [two weeks ago @kfiroo starts to maintaining the component](https://github.com/FaridSafi/react-native-gifted-chat/pull/196#issuecomment-265700341), but there are a lot of things to do, as you can see [1](https://github.com/FaridSafi/react-native-gifted-chat/pull/226#issuecomment-268228027), [2](https://github.com/FaridSafi/react-native-gifted-chat/issues/314), etc.

Meanwhile, you can inspect the [Bubble.js](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/Bubble.js) file to see how to implement your own bubble using the `renderBubble` prop and, of course, give us a hand improving the component and its documentation :)

**Comment by kfiroo** [comment]
Also, take a look at the [example](https://github.com/FaridSafi/react-native-gifted-chat/tree/master/example) project to get an idea of how to use it.
[This](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/example/App.js#L156) could be a good place to start.

@dgdavid The naming is a bit confusing maybe, `Bubble` is actually the content, and `Message` is actually the bubble
