### ISSUE TITLE
[SUGGESTION] switch momentjs for date-fns

### ISSUE THREAD

**Issue by mauron85** [FaridSafi/react-native-gifted-chat#320]
#### Issue Description

MomentJS is very large library. My suggestion is to replace it with date-fns, which is much smaller.
The only downside is that date-fns doesn't support fully localized date formats. But personally I prefer size of bundle over localized formats. If somebody requires special date format, it can be done by overriding renderMessage, renderTime ... methods).

#### Additional Information

I've initial work on this. Not sending as PR, because it needs more discussion.

https://github.com/mauron85/react-native-gifted-chat/tree/feature/date-fns

**Comment by dgdavid** [comment]
@mauron85 I agree with you. In fact, this is also what I was thinking about since I follow the [date-fn](https://github.com/date-fns/date-fns) project. But I was waiting to @kfiroo organize and share his todo list with us and also after Xmas/busy dates.

In other hand, in my project I'm using also [`Moment Timezone`](http://momentjs.com/timezone/) because we are storing dates in UTC and displaying it in the user timezone and I think that `date-fn` has not an alternative for this right now.

BTW, I like also the [`date-fn` Contribution Guidelines](https://date-fns.org/docs/Contributing)

**Comment by kfiroo** [comment]
@mauron85 I caught the buzz around `date-fns` too but I really don't think js file size is a big issue with react-native apps.

I think some people are using `moment`s functionality and I wouldn't want to cause "unnecessary" regressions.

That being said, a PR that maintains the current functionality with better code is always welcome! :)

**Comment by mauron85** [comment]
I don't agree, but respect your decision. ;-)

**Comment by kfiroo** [comment]
@mauron85 It's not a decision it's a discussion :)
What don't you agree with?

**Comment by mauron85** [comment]
IMHO size matter. However my kung fu is not that strong to give super convincing argument. In browser larger bundle means slower parsing, larger memory footprint, more GCs... 
Correct me if I'm wrong but RN uses same JS engine (V8, ...) as mobile browser.

**Comment by chrise86** [comment]
I've somehow stumbled upon this discussion while researching performance with `RN` and `moment`. I was facing a very weird rendering glitch with `FlatList`, and RN was in fact reporting a rendering performance issue - which turned out to be due to `moment` date formatting. I decided to try `date-fns` and it solved all my problems! Not sure if that helps to sway the discussion here, but it certainly helped in my situation.

**Comment by tonyhb** [comment]
+1.  Will see about getting to this soon.
