### ISSUE TITLE
Video calling (perhaps using WebRTC as the API)

### ISSUE THREAD

**Issue by balupton** [FaridSafi/react-native-gifted-chat#44]
Wondering if there are any plans for this, as it is something I'm quite interested in.

**Comment by FaridSafi** [comment]
Hello @balupton, I don't plan to implement this feature but pull request is welcome

**Comment by wenkesj** [comment]
@FaridSafi I have been working on a large Application and have amounted React Native modules that work very well with the `gifted messenger` tooling. Would you be open to a community/group based around `gifted-*` components? I would be very interested in seeing what you and @balupton could do for the community.

**Comment by FaridSafi** [comment]
@wenkesj Sure, what platform do you suggest for this group?

**Comment by wenkesj** [comment]
iOS, Android and Web for React Native

**Comment by balupton** [comment]
That sounds interesting.

**Comment by reformer** [comment]
@wenkesj ,
Hi have you port GiftedMessanger on Web? I doing it since many days but no luck. After lot of researching and understanding i stuck on problem,

 [482] ./styles.js 8.56 kB {0} [built]
[483] ./GiftedMessengerContainer.js 12.3 kB {0} [built] [1 error]
[485] ./~/react-native-communications/AKCommunications.js 3.75 kB {0} [built]
[486] ./~/react-native-extra-dimensions-android/index.js 379 bytes {0} [built]
[487] ./home_web.js 4.24 kB {0} [built]
[488] ./img/logo.png 82 bytes {0} [built]

ERROR in ./~/react-native-gifted-messenger/GiftedMessenger.js
Module parse failed: D:\React_Practices\MyCode\Project\node_modules\react-native-gifted-messenger\GiftedMessenger.js
Unexpected token (397:10)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (397:10)

My web.config loaders is ,

module: {
    loaders: [
                  {
      test: /\.jsx?$/,
      loaders: ['react-hot', 'babel-loader?presets[]=es2015,presets[]=react'],
      include: [config.paths.src],
      exclude: [/node_modules/]
                  },
    {
      test: /\.css$/,
      loader: "style-loader!css-loader"
    },
                {
      test: /.*\.(gif|png|jpe?g|svg)$/i,
      loader: 'file-loader'
    }],
    resolve: {
      extensions: ['.js', '.jsx']
    }
  }


My package.json is 

"dependencies": {
    "react": "0.14.8",
    "react-web": "0.2.4",
    "react-dom": "0.14.7",
    "react-native": "0.23.1",
    "react-art": "0.14.0",
     "socket.io-client": "1.3.7",
    "react-router": "2.4.1",
    "@exponent/react-native-navigator": "0.4.2",
    "react-native-incall-manager": "1.1.0",
    "react-native-extra-dimensions-android": "^0.17.0",
    "react-native-gifted-messenger": "*"
  },
  "devDependencies": {
    "babel-core": "6.9.0",
    "babel-loader": "6.2.4",
    "babel-preset-es2015": "6.6.0",
    "babel-preset-react": "6.5.0",
    "react-hot-loader": "1.3.0",
    "webpack": "1.13.0",
    "webpack-dev-server": "1.14.1",
    "haste-resolver-webpack-plugin": "0.1.2",
    "webpack-html-plugin": "0.1.1",
    "css-loader": "0.23.1",
    "style-loader": "0.13.1",
                "file-loader": "0.8.5"
  }

According to error i stuck on line  <View style={this.styles.loadEarlierMessages}> from,

renderLoadEarlierMessages() {
if (this.props.loadEarlierMessagesButton) {
if (this.props.isLoadingEarlierMessages) {
return (
<View style={this.styles.loadEarlierMessages}>
<GiftedSpinner />
</View>
);
}

Thanks

**Comment by sibelius** [comment]
@reformer could u share your repo for the web version of this component?

**Comment by c3zi** [comment]
What is the status of video/audio call?
