### ISSUE TITLE
imageStyle passed in renderAvatar doesn't apply to avatar placeholder

### ISSUE THREAD

**Issue by robinheinze** [FaridSafi/react-native-gifted-chat#541]
#### Issue Description

When passing a custom image size to Avatar, the size doesn't also apply to the placeholder that appears when the messages is from the same user on the same day.

#### Steps to Reproduce / Code Snippets

I'm passing custom styles to Avatar via `renderAvatar`: 
```
  renderAvatar = (props) => {
    return (
      <Avatar
        {...props}
          imageStyle={{
            height: 40,
            width: 40,
            borderRadius: 20,
            bottom: 8
         }}
      />
    )
  }
```
However, I notice that in the case of same user/ same day messages, the placeholder that is rendered uses the default 36x36 sizes.

![screen shot 2017-08-15 at 11 30 16 am](https://user-images.githubusercontent.com/6894653/29330140-23a970aa-81ad-11e7-8b09-293fc73ce36c.png)

I believe the issue lies here https://github.com/FaridSafi/react-native-gifted-chat/blob/4d11276e993eb17429dff77dea5e166913acbec9/src/Avatar.js#L31 

The logic that renders `GiftedAvatar` without a user based on the result of `isSameDay` and `isSameUser` bypasses `this.renderAvatar`, which is where the `renderAvatar` from props is called. If the section of logic that checks for same day/same user were moved to line 14, within `this.renderAvatar`, I think it would solve the issue.

#### Expected Results

Passing custom styles to Avatar also affects the placeholder. 

#### Additional Information

* React Native version:  0.46.4
* react-native-gifted-chat version: 0.2.5
* Platform(s) (iOS, Android, or both?): Both

**Comment by brunocascio** [comment]
Related to https://github.com/FaridSafi/react-native-gifted-chat/issues/308

**Comment by melyux** [comment]
Not stale, still happening. @FaridSafi

**Comment by Eonsinde** [comment]
You shouldn't mark the issue as STALE, it is still very much happening and should be looked into. I've tried every workaround possible, all to no avail. That damned placeholder will always be rendered for each Message component where the renderAvatar isn't called. Please help resolve. The issue is clearly stemming from the fact that Gifted Chat internally renders the default placeholder(36x36 pixels) in the Message component anytime the isSameThread condition is true(i.e the First Message in a given thread). PLEASE DONOT MARK AS STALE, HELP RESOLVE
