### ISSUE TITLE
Phone Number link not getting whole phone number

### ISSUE THREAD

**Issue by brunolemos** [FaridSafi/react-native-gifted-chat#565]
#### Issue Description

Check the last messages, there seem to be an limit on the phone number digits count:

![image](https://user-images.githubusercontent.com/619186/30144656-eb531a18-9362-11e7-87b7-2d8a65b26153.png)

#### Steps to Reproduce / Code Snippets

Send message with a big phone number, e.g. +5516981216190

#### Expected Results

Highlight whole phone number

#### Additional Information

* React Native version: 0.48.1
* react-native-gifted-chat version: 0.2.7
* Platform(s) (iOS, Android, or both?): iOS

**Comment by cooperka** [comment]
Hi @brunolemos, I think this is due to the parsing library being used. The issue is probably best opened with them: https://github.com/taskrabbit/react-native-parsed-text

Until then, you can override and use custom parsing logic via this recent PR (currently on master but unreleased): https://github.com/FaridSafi/react-native-gifted-chat/pull/551. There's an example there, please let me know if this works for you.

**Comment by brunolemos** [comment]
Cool, thanks. Made a [PR](https://github.com/taskrabbit/react-native-parsed-text/pull/36) there for now.
