### ISSUE TITLE
FR: Allow rendering a "No Messages" screen inside Gifted Chat

### ISSUE THREAD

**Issue by brunolemos** [FaridSafi/react-native-gifted-chat#607]
When there is 0 messages, I'd like to be able to show a custom view (with the "Type message" still showing below), for example:

<img src="https://user-images.githubusercontent.com/619186/31728610-7e9b4d68-b40b-11e7-8e6a-92763c3c9e8a.png" width="300" />

**Comment by vgorte** [comment]
Hello @brunolemos,
it would be great if you could specify your title by adding a description.
I guess you want something like #575 .

**Comment by brunolemos** [comment]
@vgorte: added a screenshot in the description

**Comment by vgorte** [comment]
Thank you for editing your description @brunolemos. 

I think the easiest way to implement this is by creating your own TitleScreen component or whatever you want to call it and render it inside as a footer instead of the typing indicator. 

It could look something like this: 
(Note that I hacked this quickly in 5 minutes so it may look shitty and unorganized since I copied parts of the component from an existing project of mine and didn't have time to clean it up)
```
import React from 'react';
import {
  Linking,
  Platform,
  StyleSheet,
  View,
  Text,
  Image
} from 'react-native';

export default class TitleMessage extends React.Component {

  render() {
      return (
        <View style={styles.container}>
          <Text style ={styles.name}> You matched with Andreia!</Text>
          <Text style ={styles.text}> 4 months ago</Text>
          <View>
            <View style={{paddingBottom: 10}}>
              <Image style={{height: 130, borderRadius: 65, width: 130}}
                source={{uri: 'https://cdn.pixabay.com/photo/2013/07/13/12/06/woman-159169_1280.png'}}
              />
            </View>
          <Text style={styles.name}>
            Message her!
          </Text>
          </View>
        </View>
      );
    }
  }


  const styles = StyleSheet.create({
   container: {
     flex: 1,
     justifyContent: 'center',
     alignItems: 'center',
     backgroundColor: 'white',
   },
   name: {
     fontFamily: "Helvetica",
     fontSize: 18,
     textAlign: 'center',
     color: '#312E31',
   },
   text: {
     fontFamily: "Helvetica",
     fontSize: 18,
     textAlign: 'center',
     color: '#949194',
   },
 });

```

You need to import this component into your App.js and change the renderFooter according to your needs. For demonstration purposes I used something like : 

```
  renderFooter(props) {
    if (this.state.titlemessage) {
      return (
          <TitleMessage />
      );
    }
    return null;
  }
```

Note that this is very bad coding style but it is sufficient for my example. 
You can add a condition to only show it when the `messages[]` is empty.

What you get looks like this: 

![simulator screen shot 18 10 2017 22 01 11](https://user-images.githubusercontent.com/17333517/31739938-e5e189da-b44f-11e7-9b4b-5a4f66c26ffe.png)


I hope this was kind of helpful.

**Comment by brunolemos** [comment]
@vgorte Thanks, that is helpful.
Although by using `renderFooter` we won't be able to put it at the center, right?

I think in the end, for now, I'll have to put the view outside GiftedChat and use position absolute to move it to the right place...

I'd like to suggest a `renderEmptyMessages` method or something like that.

**Comment by brunolemos** [comment]
So using `position: absolute` together with `renderChatFooter` worked pretty well,
here is the final solution:

```
renderChatFooter={() =>
  !messages.length && (
    <LoadMessagesError
      icon={Platform.select({
        ios: 'ios-heart-outline',
        android: 'favorite-border',
      })}
      onPress={() => {
        if (this.state.keyboardIsVisible) Keyboard.dismiss()
        else if (this.giftedChatRef)
          this.giftedChatRef.focusTextInput()
      }}
      text="Be the first one to send a message"
      style={styles.giftedChatOverlay}
    />
  )}
```

```
const styles = StyleSheet.create({
  giftedChatOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
  },
})
```

<img src="https://user-images.githubusercontent.com/619186/31744197-ab25ed76-b43c-11e7-8339-eb451d769e0e.png" width="300" />
