### ISSUE TITLE
Problem with Starting up in Android (intellij idea)

### ISSUE THREAD

**Issue by amonemian** [FaridSafi/react-native-gifted-chat#631]
#### Issue Description
can not run the project (Android)

#### Steps to Reproduce / Code Snippets

Failed to parse source list at https://dl.google.com/android/repository/addons_list-3.xml
Errors during XML parse:
White spaces are required between publicId and systemId.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-maps'.
      > java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 25.793 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

* React Native version: 0.46.3
* react-native-gifted-chat version: 3.0
* Platform(s) (iOS, Android, or both?): android

**Comment by MehdiAlouafi** [comment]
I think that this is not related to this particular module, I searched a little and one of the possible reason for this bug is a corrupted gradle file. The problem may be located in your .gradle file.

See this : 

- https://github.com/mauron85/react-native-background-geolocation/issues/52
- https://stackoverflow.com/questions/41546761/could-not-resolve-all-dependencies-for-configuration-app-debugapk-configurat

Possible solutions : 

- check every depencies in your settings.gradle
- delete the android/.gradle gitignored folder and restart / recompile / rebuild

**Comment by xcarpentier** [comment]
As @MehdiAlouafi  it's said related to this package ... I guess too.
So I close it but if you find a related please feel free to re-open.
:)
