### ISSUE TITLE
TypeError: Cannot read property 'setState' of undefined

### ISSUE THREAD

**Issue by Yohann-Chen** [FaridSafi/react-native-gifted-chat#725]
#### Issue Description
I use NativeModules to choice photo.but when I got the photo,use `this.setState({source:image.path})` to change the photo,but throw a warning
`TypeError: Cannot read property 'setState' of undefined`
It seems to be the scope of action？
so what should I do?

#### Steps to Reproduce / Code Snippets

```
 _renderActions(props) {
        
      const options = {
        
        'Camera': (props) => {
          
          ImagePicker.openCamera({
              compressImageQuality : 0.8
          }).then(image => {
            this.setState({
                  source : image.path
              })
          });
        },
        'Photo': (props) => {
          
          ImagePicker.openPicker({
              compressImageQuality : 0.8,
              smartAlbums : ['UserLibrary','PhotoStream','Bursts']
          }).then(image => {
              this.setState({
                  source : image.path
              })
          });
        },
        'Cancel': () => {},
      };
      return (
        <Actions
          {...props}
          options={options}
          icon={()=>{return <Image source={{uri:'chat_photo',width:30,height:30}}/>}}
        />
      );
    }
```

#### Expected Results
![image](https://user-images.githubusercontent.com/13533355/35206925-dfeb4b1c-ff7a-11e7-8db1-2bdc5eb12a2e.png)
![image](https://user-images.githubusercontent.com/13533355/35206929-ea0e713c-ff7a-11e7-89a6-0284f3f9dfcf.png)

#### Additional Information

* Nodejs version: v8.9.1
* React version: 16.0.0-alpha.12
* React Native version: 0.48.0
* react-native-gifted-chat version: 0.3.0
* Platform(s) (iOS, Android, or both?): iOS

**Comment by MehdiAlouafi** [comment]
Hi !

This issue is not related to this module. It is because your `_renderActions` does not have the right context (this). if you console.log `this` inside _renderActions you will have what is available on the global space (such as fetch, alert, ...) but not your component.

A solution will be to simply bind your _renderActions function to your component context

try to add this on the constructor : 

```
class YourClass extends Component {
   constructor() {
     super();
     this._renderActions = this._renderActions.bind(this);
  }
```

You can also use the arrow function syntax for your class methods in order to bind automatically.

**Comment by Yohann-Chen** [comment]
I've solved this problem. Thank you. @MehdiAlouafi

**Comment by addicus178** [comment]
This is due to this.delta not being bound to this.

In order to bind set this.delta = this.delta.bind(this) in the constructor:

constructor(props) {
super(props);

this.state = {
count : 1
};

this.delta = this.delta.bind(this);
}

Full Source With Example Is [Here](https://icetutor.com/question/react-uncaught-typeerror-cannot-read-property-setstate-of-undefined/)
