### ISSUE TITLE
How to set  message  position is  left or right without user id?

### ISSUE THREAD

**Issue by tonnth** [FaridSafi/react-native-gifted-chat#779]
#### Issue Description

How to set  message  position is  left or right without user id?
Thank you in advance!

**Comment by cuongnguyen1996** [comment]
@xcarpentier Will easily to decide bubble left or right if add 'position' property to message object.
Now it depend on 'user._id' property in message object.
I hope it in next release.

**Comment by joaodematejr** [comment]
+1

**Comment by joaodematejr** [comment]
same problem here @cuongnguyen1996

**Comment by xcarpentier** [comment]
Hello,
good idea, 
PR are welcome

**Comment by joaodematejr** [comment]
I am trying to do this test to start a message on the right side but it is not working could you help me please @xcarpentier 

componentDidMount() { this.setState({ messages: [ { _id: 1, position: 'right', text: 'Hello developer', createdAt: new Date(), user: { _id: 1, name: 'React Native', avatar: 'https://placeimg.com/140/140/any', }, }, ] }) }

**Comment by IdealSystemsMCP** [comment]
@xcarpentier I tried creating a PR, but I can't commit due to some TypeScript errors (which I'm not familiar with)

My idea was to add a prop:
```javascript
export interface GiftedChatProps<TMessage extends IMessage = IMessage> {
  // ...
  /* Custom callback to change position of message */
  getIsPositionRight(message: IMessage, user: User): boolean
}
```
which has the old way as default value (to not break anything)
```javascript
static defaultProps = {
  // ...
  getIsPositionRight: (message: IMessage, user: User) => message.user._id === user._id,
}
```
and then use it here: [MessageContainer](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/MessageContainer.tsx#L296)
```javascript
// position: item.user._id === user._id ? 'right' : 'left',
position: getIsPositionRight(item, user) ? 'right': 'left',
```
This way it'll work as before, but if some users want to change the functionality they can give it a custom getIsPositionRight function, like:
```javascript
<GiftedChat
  //...
  getIsPositionRight={(message, user) => message.user.type === 'AGENT'}
/>
```
