### ISSUE TITLE
Opposite Scroll Logic

### ISSUE THREAD

**Issue by s5963028** [FaridSafi/react-native-gifted-chat#998]
#### Issue Description

If i set inverted flag to false, then after i send a message (onSend function), the list scrolls to top and I need to scroll all the way down to see my new message.

If i set inverted flag to true, then after i send a message (onSend function), the list scrolls to bottom and I need to scroll all the way up to see my new message.

#### Steps to Reproduce / Code Snippets

Just make a list with enough messages to make screen scroll

#### Expected Results

inverted flag == false, then screen will remains always in bottom part.
inverted flag == true, then screen will remains always in upper part.

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: 16.4.1
* React Native version: 0.56.0
* react-native-gifted-chat version: 0.4.3
* Platform(s) (iOS, Android, or both?): BOTH

**Comment by kanso-michael** [comment]
Think this is because of calling `scrollToOffset` on a `FlatList`
https://github.com/FaridSafi/react-native-gifted-chat/blob/052094d4dd1f2cd2726454605cf53ff115b5b9fa/src/MessageContainer.js#L82

It is passing through `y: 0` in the `options` object
https://github.com/FaridSafi/react-native-gifted-chat/blob/1fedba2203e29d35832e4939e1857f44ab398ab9/src/GiftedChat.js#L301

FlatList docs state:
https://facebook.github.io/react-native/docs/flatlist#scrolltooffset

```
Valid params keys are:

'offset' (number) - The offset to scroll to. In case of horizontal being true, the offset is the x-value, in any other case the offset is the y-value. Required.
'animated' (boolean) - Whether the list should do an animation while scrolling. Defaults to true.
```

I don't currently have time for a full fix right now, but my suggestion if you need this working asap and you are using `inverted=false`, is to swap `scrollToOffset` to `scrollToEnd`.
